name: Create and Upload Release Assets

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    runs-on: ubuntu-22.04
    permissions:
      # 需要写入权限来创建 Release 和上传附件
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有历史记录，以便比较分支

      - name: Check if tag is on the main branch
        id: check_branch
        run: |
          main_sha=$(git rev-parse origin/main)
          tag_sha="${{ github.sha }}"
          if [ "$tag_sha" == "$main_sha" ]; then
            echo "✅ Tag is on the main branch. Proceeding."
            echo "is_on_main=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Tag is NOT on the main branch head. Skipping."
            echo "is_on_main=false" >> $GITHUB_OUTPUT
          fi

      - name: Get version from tag
        if: steps.check_branch.outputs.is_on_main == 'true'
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Create version.json
        if: steps.check_branch.outputs.is_on_main == 'true'
        run: |
          echo '{ "version": ${{ env.VERSION }} }' > version.json
          echo "Created version.json with content:"
          cat version.json

      - name: Create zip archive
        if: steps.check_branch.outputs.is_on_main == 'true'
        run: zip -r Protoshield.zip . -x ".git/*" ".github/*"

      - name: Create Release and Upload Assets
        if: steps.check_branch.outputs.is_on_main == 'true'
        uses: softprops/action-gh-release@v2
        with:
          # 将 version.json 和 Protoshield.zip 作为附件上传
          files: |
            version.json
            Protoshield.zip
          # 使用 tag 作为 Release 的名称
          name: Release ${{ github.ref_name }}
          # 自动生成 Release notes
          generate_release_notes: true
